### ISSUE TITLE
Невозможно создать кредитный счет с нулевой ставкой кредитования

### ISSUE THREAD

**Issue by hellen0874** [hellen0874/TeamProject#1]
# Описание
При попытке создать счет с нулевой процентной ставкой выдается сообщение "Накопительная ставка не может быть отрицательной, а у вас: 0"

# Локация дефекта
https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/584960f44a943ace8420f70dc5c27279da2da619/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA;
2. Создать новый счет (объект класса `CreditAccount`), в параметрах указав значение ставки кредитования, равное 0;

*Ожидаемый результат:* создание счета со ставкой кредитования, равной нулю
*Фактический результат:* счет не создается, выдается сообщение : "Накопительная ставка не может быть отрицательной, а у вас: 0"
*Проверяющий тест:* [№ 1.5](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#LL56C4-L56C45)

# Скриншоты
![Скрин к issue 1](https://github.com/hellen0874/TeamProject/assets/109699459/322803f5-fb4a-4eb8-9826-d84f8f0c3118)

![Скрин2 к issue 1](https://github.com/hellen0874/TeamProject/assets/109699459/08c64f6a-18df-480c-be17-c6b6d254b5cf)

# Окружение
* **Операционная система:** Windows 11 Домашняя для одного языка,
*  **IDE:** IntelliJ IDEA 2022.3 (Community Edition),
*  **Java:** OpenJDK 11

@Tatulenciya

**Comment by Tatulenciya** [comment]
# Исправленное

https://github.com/hellen0874/TeamProject/blob/0509fbbde34b6e422cb992046eecb2de9983c6e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19
