### ISSUE TITLE
Не выдает ошибку при создании нового объекта сберегательного счета, если начальный баланс больше максимального баланса.

### ISSUE THREAD

**Issue by Tatulenciya** [hellen0874/TeamProject#13]
# Описание
При создании нового объекта сберегательного счета с заданными параметрами должно выкидываться исключение вида IllegalArgumentException, если начальный баланс больше максимального баланса. 

# Локация дефекта
https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать новый объект  **SavingAccount** сберегательного счёта с параметрами:
 * initialBalance = 15000
 * minBalance = 1000
 * maxBalance = 10000
 * rate = 5

*Ожидаемый результат:* На экране отобразится исключение вида IllegalArgumentException. **"Начальный баланс не может быть больше максимального"**
*Фактический результат:* Отсутствие данной ошибки
Тесткейс: [shouldShowErrorIfInitialBalanceMoreMaxBalance](https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#LL154C17-L154C62)

# Скриншот
![image](
https://github.com/hellen0874/TeamProject/assets/127183387/460efd56-a4d3-4900-8e6c-61b70e19ba4e
)

# Окружение
* **Операционная система:** macOS Ventura 13.0.1
* **IDEA:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** OpenJDK 11

@hellen0874

**Comment by hellen0874** [comment]
Исправлено:
https://github.com/hellen0874/TeamProject/blob/200f65fdc12af4542b4f24620724058bbc72b2d5/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L49-L52
