### ISSUE TITLE
Проценты на отрицательный баланс начисляются не по требуемым правилам (кредитный счет)

### ISSUE THREAD

**Issue by hellen0874** [hellen0874/TeamProject#14]
# Описание 
После создания отрицательного баланса на счете и вызова метода `yearChange` вычисление процентов не соответствует результатам примера в описании метода.
Возможно, проблема связана с ошибкой по issue #4, #5,  #6 

# Локация дефекта 
https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) (`CreditAccount.java`) в IDEA;
2. Создать новый счет (объект класса `CreditAccount`), в параметрах указав значение начального баланса (`initialBalance`), равное 3000, значение ставки кредитования (`rate`), равное 15, лимит кредитования - положительный;
3. Вызвать метод `pay`, указав значение параметра `amount`, равное 3200
4. Вызвать метод `yearChange`

*Ожидаемый результат:* конечный баланс операции равен -200 (баланс уменьшается на сумму оплаты), начисленные проценты равны -30
*Фактический результат:* размер начисленных процентов равен -480

*Проверяющий тест:* [№ 4.1](https://github.com/hellen0874/TeamProject/blob/a39e40a92a4daa95599baf7ab9624cf0f403a903/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#LL270C7-L270C7)

# Скриншоты
![Скрин к issue 8](https://github.com/hellen0874/TeamProject/assets/109699459/2884a379-1dac-4661-82b7-d3814deb3344)

![Скрин2 к issue 8](https://github.com/hellen0874/TeamProject/assets/109699459/caf6bd75-0714-482e-857a-346f93197f8f)

Возможно, проблема связана с этим:
![Скрин2 к issue 4](https://github.com/hellen0874/TeamProject/assets/109699459/e6d16984-eded-4548-aa6f-e950e7102236)

# Окружение
* **Операционная система:** Windows 11 Домашняя для одного языка,
*  **IDE:** IntelliJ IDEA 2022.3 (Community Edition),
*  **Java:** OpenJDK 11

@Tatulenciya

**Comment by Tatulenciya** [comment]
# Исправлено

https://github.com/hellen0874/TeamProject/blob/0509fbbde34b6e422cb992046eecb2de9983c6e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L89
