### ISSUE TITLE
Начисляются проценты при положительном балансе и ставке кредитования 15 (кредитный счет)

### ISSUE THREAD

**Issue by hellen0874** [hellen0874/TeamProject#15]
# Описание 
После создания счета с положительным балансом (`initialBalance`) 200 и вызова метода `yearChange` происходит вычисление процентов.

# Локация дефекта 
https://github.com/hellen0874/TeamProject/blob/0e7cbe11757a595f014be6ef9a2d996e5882b5f3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) (`CreditAccount.java`) в IDEA;
2. Создать новый счет (объект класса `CreditAccount`), в параметрах указав значение начального баланса (`initialBalance`), равное 200, значение ставки кредитования (`rate`), равное 15, лимит кредитования - положительный;
3. Вызвать метод `yearChange`

*Ожидаемый результат:* проценты не начисляются
*Фактический результат:* размер начисленных процентов равен -30

*Проверяющий тест:* [№ 4.3](https://github.com/hellen0874/TeamProject/blob/0e7cbe11757a595f014be6ef9a2d996e5882b5f3/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#LL295C11-L295C11)

# Скриншоты
![Скрин1 к issue 9](https://github.com/hellen0874/TeamProject/assets/109699459/9561d4bb-2175-4215-92b1-dbab291ba1c4)

![Скрин2 к issue 9](https://github.com/hellen0874/TeamProject/assets/109699459/dcb47f96-a371-47c4-ab33-496c7ce19064)

# Окружение
* **Операционная система:** Windows 11 Домашняя для одного языка,
*  **IDE:** IntelliJ IDEA 2022.3 (Community Edition),
*  **Java:** OpenJDK 11

@Tatulenciya

**Comment by Tatulenciya** [comment]
# Исправлено

https://github.com/hellen0874/TeamProject/blob/0509fbbde34b6e422cb992046eecb2de9983c6e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L88
