### ISSUE TITLE
Не производится пополнение счета при выполнении условия, что баланс после пополнения меньше максимального

### ISSUE THREAD

**Issue by Tatulenciya** [hellen0874/TeamProject#16]
# Описание
При пополнении сберегательного счета баланс не изменяется.  

# Локация дефекта
https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать новый объект сберегательного счёта с параметрами:
 * initialBalance = 2000
 * minBalance = 1000
 * maxBalance = 10000
 * rate = 5
3. Пополнить счет на 3000 используя метод **add**.

*Ожидаемый результат:* баланс равен 5000.
*Фактический результат:* баланс стал равен сумме покупки. 
Тесткейс: [shouldAddLessThanMaxBalance](https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#LL11C17-L11C44)

# Скриншот
![image](
https://github.com/hellen0874/TeamProject/assets/127183387/1caf8051-9c70-41e3-a9ca-d32e97242bd1
)

![image](
https://github.com/hellen0874/TeamProject/assets/127183387/ffdc9632-5528-4eb6-adb2-038cf8343bd3
)

# Окружение
* **Операционная система:** macOS Ventura 13.0.1
* **IDEA:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** OpenJDK 11

@hellen0874

**Comment by hellen0874** [comment]
Исправлено:
https://github.com/hellen0874/TeamProject/blob/200f65fdc12af4542b4f24620724058bbc72b2d5/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L104-L105
