### ISSUE TITLE
Операция оплаты с карты приводит к отрицательному балансу на сберегательном счете. 

### ISSUE THREAD

**Issue by Tatulenciya** [hellen0874/TeamProject#17]
# Описание
После выполнении операции оплаты с карты на сумму покупки больше начального баланса, баланс счета становится отрицательным.  

# Локация дефекта
https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать новый объект  сберегательного счёта с параметрами:
 * initialBalance = 5000
 * minBalance = 1000
 * maxBalance = 10000
 * rate = 5
3. Оплатить покупку на сумму 6000 вызвав метод **pay**.

*Ожидаемый результат:* Баланс не изменится, так как сумма покупки больше начального баланса
*Фактический результат:* Баланс равен -1000. 
Тесткейс: [payIfAmountMoreInitialBalance](https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#LL178C17-L178C46)

# Скриншот
![image](
https://github.com/hellen0874/TeamProject/assets/127183387/588e93f9-fba1-454e-b00c-856f7acdc32c
)

# Окружение
* **Операционная система:** macOS Ventura 13.0.1
* **IDEA:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** OpenJDK 11

@hellen0874

**Comment by hellen0874** [comment]
Исправлено:
https://github.com/hellen0874/TeamProject/blob/200f65fdc12af4542b4f24620724058bbc72b2d5/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L75-L77
