### ISSUE TITLE
Возможно создать кредитный счет с отрицательным начальным балансом

### ISSUE THREAD

**Issue by hellen0874** [hellen0874/TeamProject#2]
# Описание 
При попытке создать счет с некорректным параметром - отрицательным изначальным балансом, ошибки не выдается. По условиям начальный баланс должен быть неотрицательным

# Локация дефекта 
https://github.com/hellen0874/TeamProject/blob/584960f44a943ace8420f70dc5c27279da2da619/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/584960f44a943ace8420f70dc5c27279da2da619/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) (`CreditAccount.java`) в IDEA;
2. Создать новый счет (объект класса `CreditAccount`), в параметрах указав значение начального баланса (`initialBalance`), равное -1;

*Ожидаемый результат:* счет не создается, выдается сообщение об ошибке
*Фактический результат:* сообщение об ошибке не выдается, счет создан.

*Проверяющий тест:* [№ 1.7](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#LL80C3-L80C55)

# Скриншот

![Скрин1 к issue 2](https://github.com/hellen0874/TeamProject/assets/109699459/4ddced6a-fe26-45c5-9055-047989bec356)

![Скрин2 к issue 2](https://github.com/hellen0874/TeamProject/assets/109699459/4fc483d3-ebf1-4ce1-bb51-f9dd05a2dd97)

# Окружение
* **Операционная система:** Windows 11 Домашняя для одного языка,
*  **IDE:** IntelliJ IDEA 2022.3 (Community Edition),
*  **Java:** OpenJDK 11

@Tatulenciya

**Comment by Tatulenciya** [comment]
# Исправлено

https://github.com/hellen0874/TeamProject/blob/0509fbbde34b6e422cb992046eecb2de9983c6e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L26
