### ISSUE TITLE
Операция оплаты с карты приводит к некорректному балансу.

### ISSUE THREAD

**Issue by Tatulenciya** [hellen0874/TeamProject#20]
# Описание
После выполнении операции оплаты с карты на сумму покупки меньше начального баланса, баланс счета становится меньше минимального значение. Что не соответствует условиям.  

# Локация дефекта
https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать новый объект  сберегательного счёта с параметрами:
 * initialBalance = 5000
 * minBalance = 1000
 * maxBalance = 10000
 * rate = 5
3. Оплатить покупку на сумму 4500 вызвав метод **pay**.

*Ожидаемый результат:* Баланс не изменится, так как операция оплаты приведет к некорректному значению баланса. 
*Фактический результат:* Баланс равен 500. 
Тесткейс: [payIfAmountLessInitialBalanceButResultLessMinBalance](https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#LL193C17-L193C69)

# Скриншот
![image](
https://github.com/hellen0874/TeamProject/assets/127183387/408e66f7-b1d0-4c0b-b833-3fbb192ab5e7
)

# Окружение
* **Операционная система:** macOS Ventura 13.0.1
* **IDEA:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** OpenJDK 11

@hellen0874

**Comment by hellen0874** [comment]
Исправлено:
https://github.com/hellen0874/TeamProject/blob/200f65fdc12af4542b4f24620724058bbc72b2d5/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L78-L82
