### ISSUE TITLE
Возможно создать кредитный счет с отрицательным кредитным лимитом

### ISSUE THREAD

**Issue by hellen0874** [hellen0874/TeamProject#3]
# Описание 
При попытке создать счет с некорректным параметром - отрицательным кредитным лимитом, ошибки не выдается. По условиям кредитным лимитом должен быть неотрицательным

# Локация дефекта 
https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) (`CreditAccount.java`) в IDEA;
2. Создать новый счет (объект класса `CreditAccount`), в параметрах указав значение кредитного лимита (`creditLimit`), равное -5000;

*Ожидаемый результат:* счет не создается, выдается сообщение об ошибке
*Фактический результат:* сообщение об ошибке не выдается, счет создан.

*Проверяющий тест:* [№ 1.8](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#LL93C5-L94C1)

# Скриншот

![Скрин1 к issue 3](https://github.com/hellen0874/TeamProject/assets/109699459/1c6f9a92-f4c0-47fc-8e5b-903d4ac2197d)

![Скрин2 к issue 2](https://github.com/hellen0874/TeamProject/assets/109699459/cc627704-c3c3-42a1-9e47-0f42fb4e9b05)

# Окружение
* **Операционная система:** Windows 11 Домашняя для одного языка,
*  **IDE:** IntelliJ IDEA 2022.3 (Community Edition),
*  **Java:** OpenJDK 11

@Tatulenciya

**Comment by Tatulenciya** [comment]
# Исправлено 

https://github.com/hellen0874/TeamProject/blob/0509fbbde34b6e422cb992046eecb2de9983c6e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L29
