### ISSUE TITLE
Неправильный расчет конечного баланса кредитного счета после оплаты при положительном конечном балансе

### ISSUE THREAD

**Issue by hellen0874** [hellen0874/TeamProject#4]
# Описание 
При вызове метода `pay` c положительной суммой покупки (ожидаемый конечный баланс положительный), неправильно производится расчет конечного баланса: баланс уменьшается не на сумму покупки

# Локация дефекта 
https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) (`CreditAccount.java`) в IDEA;
2. Создать новый счет (объект класса `CreditAccount`), в параметрах указав значение начального баланса (`initialBalance`), равное 3000, остальные параметры - неотрицательные;
3. Вызвать метод pay, указав значение параметра `amount`, равное 1300
4. Вызвать метод `getBalance`

*Ожидаемый результат:* конечный баланс операции равен 1700 (баланс уменьшается на сумму покупки)
*Фактический результат:* конечный баланс операции равен -1300 (баланс уменьшается не на сумму покупки)

*Проверяющий тест:* [№ 2.1](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#LL120C5-L120C61)

# Скриншоты
![Скрин1 к issue 4](https://github.com/hellen0874/TeamProject/assets/109699459/b90f7d6b-9a3b-44c3-b583-b9598b3a3ec3)

![Скрин2 к issue 4](https://github.com/hellen0874/TeamProject/assets/109699459/21d0c428-e290-4715-91d3-a6d885a0c0c9)

# Окружение
* **Операционная система:** Windows 11 Домашняя для одного языка,
*  **IDE:** IntelliJ IDEA 2022.3 (Community Edition),
*  **Java:** OpenJDK 11

@Tatulenciya

**Comment by Tatulenciya** [comment]
# Исправлено 

https://github.com/hellen0874/TeamProject/blob/0509fbbde34b6e422cb992046eecb2de9983c6e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L51
