### ISSUE TITLE
После пополнения кредитного счета при положительном начальном балансе конечный баланс увеличивается не на сумму пополнения

### ISSUE THREAD

**Issue by hellen0874** [hellen0874/TeamProject#7]
# Описание 
При вызове метода `add` c положительной суммой пополнения (ожидаемый конечный баланс положительный), неправильно производится расчет конечного баланса: баланс увеличивается не на сумму покупки

# Локация дефекта 
https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) (`CreditAccount.java`) в IDEA;
2. Создать новый счет (объект класса `CreditAccount`), в параметрах указав значение начального баланса (`initialBalance`), равное 1, остальные параметры - положительные;
3. Вызвать метод `add`, указав значение параметра `amount`, равное 3000
4. Вызвать метод `getBalance`

*Ожидаемый результат:* конечный баланс операции равен 3001 (баланс увеличивается на сумму пополнения)
*Фактический результат:* конечный баланс операции равен 3000 (баланс увеличивается не на сумму пополнения)

*Проверяющий тест:* [№ 3.2](https://github.com/hellen0874/TeamProject/blob/002133280a6cf228f61f6835328bfcddf25739da/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#LL222C5-L222C5)

# Скриншоты
![Скрин1 к issue 7](https://github.com/hellen0874/TeamProject/assets/109699459/58e71f4c-3cc1-47cb-9c30-eba42897650f)

![Скрин2 к issue 7](https://github.com/hellen0874/TeamProject/assets/109699459/2061b747-4f23-4735-abd6-05d5f86770cf)

# Окружение
* **Операционная система:** Windows 11 Домашняя для одного языка,
*  **IDE:** IntelliJ IDEA 2022.3 (Community Edition),
*  **Java:** OpenJDK 11

@Tatulenciya

**Comment by Tatulenciya** [comment]
# Исправлено

https://github.com/hellen0874/TeamProject/blob/0509fbbde34b6e422cb992046eecb2de9983c6e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L74
