### ISSUE TITLE
Ошибка в вычислениях при операции расчета процентов на остаток счета

### ISSUE THREAD

**Issue by Tatulenciya** [hellen0874/TeamProject#8]
# Описание
В результате расчета суммы процентов на остаток счета происходит не верное вычисление. 

# Локация дефекта
https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/hellen0874/TeamProject/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать новый объект сберегательного счёта с параметрами:
 * initialBalance = 5330
 * minBalance = 1000
 * maxBalance = 10000
 * rate = 5
3. Вызвать метод **yearChange**

*Ожидаемый результат:* Сумма процентов на остаток счета равна 266. 
*Фактический результат:* Сумма процентов на остаток счета равна 265
Тесткейс: [testYearChange](https://github.com/hellen0874/TeamProject/blob/76611e7dc84fe5981dcd834b84857a72127659ab/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L268)

# Скриншот
![image](
https://github.com/hellen0874/TeamProject/assets/127183387/83efd693-b1d8-4f12-baf3-1420ec9e7bab
)
![image](
https://github.com/hellen0874/TeamProject/assets/127183387/99cbd44f-3f2c-47f1-9e1a-181c19ea7c6a
)

# Окружение
* **Операционная система:** macOS Ventura 13.0.1
* **IDEA:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** OpenJDK 11

@hellen0874

**Comment by hellen0874** [comment]
Исправлено:
https://github.com/hellen0874/TeamProject/blob/200f65fdc12af4542b4f24620724058bbc72b2d5/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L121
